# Generated by Django 2.1.7 on 2019-03-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20190311_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='header',
        ),
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
