# Generated by Django 2.1.7 on 2019-03-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_answer_for_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='creation_date',
            new_name='pub_date',
        ),
    ]
