# Generated by Django 2.1.7 on 2019-03-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_auto_20190312_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(to='qa.Question'),
        ),
    ]
