# Generated by Django 2.1.7 on 2019-03-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_tag_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(blank=True, to='qa.Question'),
        ),
    ]
